// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDc8kipcUIfTO-eIExz0Nf0ZmyZHydYEo',
    appId: '1:61863467411:web:67f574d48c59f652197066',
    messagingSenderId: '61863467411',
    projectId: 'tvs-test-c8dc1',
    authDomain: 'tvs-test-c8dc1.firebaseapp.com',
    storageBucket: 'tvs-test-c8dc1.appspot.com',
    measurementId: 'G-WWVB5HFZJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBekE6QdYKLC3mN5mJ5saA1kdlYjD9hvi0',
    appId: '1:61863467411:android:0aa024fb152bbb15197066',
    messagingSenderId: '61863467411',
    projectId: 'tvs-test-c8dc1',
    storageBucket: 'tvs-test-c8dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00TGvwO6iByQrmCEGHllwwXfetwRfsXY',
    appId: '1:61863467411:ios:effeb51cf8a79f0b197066',
    messagingSenderId: '61863467411',
    projectId: 'tvs-test-c8dc1',
    storageBucket: 'tvs-test-c8dc1.appspot.com',
    iosBundleId: 'com.example.tvsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00TGvwO6iByQrmCEGHllwwXfetwRfsXY',
    appId: '1:61863467411:ios:effeb51cf8a79f0b197066',
    messagingSenderId: '61863467411',
    projectId: 'tvs-test-c8dc1',
    storageBucket: 'tvs-test-c8dc1.appspot.com',
    iosBundleId: 'com.example.tvsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDc8kipcUIfTO-eIExz0Nf0ZmyZHydYEo',
    appId: '1:61863467411:web:054f163b6b4602dd197066',
    messagingSenderId: '61863467411',
    projectId: 'tvs-test-c8dc1',
    authDomain: 'tvs-test-c8dc1.firebaseapp.com',
    storageBucket: 'tvs-test-c8dc1.appspot.com',
    measurementId: 'G-N1B85GNMQD',
  );
}
